### ISSUE TITLE
First step: Configuration

### ISSUE THREAD

**Issue by bjoernhaeuser** [andreasscherbaum/backdbup#1]
Hey,

I think the first would be to commit on a configuratioin file format. I would propose yaml for simplicity but I am open for everything else also.

I think the configuration file could look like this:

``` yaml

---
  base: 
    - postgres-master: 
        executables: "/usr/pgsql-9.2/bin/"
        staging: "/mnt/nfs"
  targets:
    - s3-bucket-xy:
        type: "s3"
        bucket-name: "your-bucket-name"
        username": ""
        accesskey": ""
    - huge-network-storage":
        type: "fs" 
        dir: "/mnt/nfs/backup"
  servers:
    -  
      type: "postgres-master"
      hostame: "postgres-server.fqdn.com"
      schedule: ???
      retention: ???
      target: "s3-bucket-xy"
```
